language: bash
services: docker

env:
  - VERSION=5.022.002-64bit VARIANT=jessie
  - VERSION=5.020.003-64bit VARIANT=jessie
  - VERSION=5.022.002-64bit VARIANT=trusty
  - VERSION=5.020.003-64bit VARIANT=trusty

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images
  - git clone https://github.com/j24cape/docker-perl-build.git ~/docker-perl-build

before_script:
  - env | sort
  - docker build -f "~/docker-perl-build/$VARIANT/Dockerfile" -t "j24cape/perl-build:$VARIANT" .
  - cd "$VERSION/$VARIANT"
  - image="j24cape/perl-build:$VERSION-$VARIANT"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
